name: AirSim Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Require new logs
        run: |
          if [[ git diff --name-only -r HEAD^1 HEAD != *"testing/AirSimTests/log/NH_auto_path_coords.txt"* ]]; then
            exit 1
          fi
