name: AirSim Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: testing/AirSimTests/log/NH_auto_path_coords.txt
      - name: Require new logs
        if: steps.changed-files.outputs.any_changed == 'false'
        run: exit 1
