name: AirSim Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        uses: tj-actions/changed-files@35
      - name: Require new logs
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [$file = "testing/AirSimTests/log/NH_auto_path_coords.txt"] then
              exit 0
            else
              echo $file
            fi
          done
          exit 1
